slice_name: Histogram - Flight Duration
description: null
certified_by: null
certification_details: null
viz_type: histogram_v2
params:
  datasource: 26__table
  viz_type: histogram_v2
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 4
  column: flight_duration_minutes
  groupby: []
  adhoc_filters: []
  row_limit: 1000
  bins: 5
  color_scheme: supersetColors
  show_legend: true
  x_axis_format: SMART_NUMBER
  y_axis_format: SMART_NUMBER
  extra_form_data: {}
  dashboards:
  - 4
query_context: '{"datasource":{"id":26,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["flight_duration_minutes"],"annotation_layers":[],"row_limit":1000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"histogram","options":{"column":"flight_duration_minutes","groupby":[],"bins":5}}]}],"form_data":{"datasource":"26__table","viz_type":"histogram_v2","matrixify_show_column_headers":true,"matrixify_mode_columns":"metrics","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_topn_order_columns":"desc","matrixify_show_row_labels":true,"matrixify_mode_rows":"metrics","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_topn_order_rows":"desc","matrixify_row_height":300,"matrixify_fit_columns_dynamically":true,"matrixify_charts_per_row":4,"column":"flight_duration_minutes","groupby":[],"adhoc_filters":[],"row_limit":1000,"bins":5,"color_scheme":"supersetColors","show_legend":true,"x_axis_format":"SMART_NUMBER","y_axis_format":"SMART_NUMBER","extra_form_data":{},"dashboards":[4],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: aa9e6290-5ea8-4756-bc33-6583f8cce954
version: 1.0.0
dataset_uuid: f43b0c26-fae5-46b5-857e-489aa7dde1bf
