slice_name: Passenger Bookings & Revenue
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 39__table
  viz_type: table
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 3
  query_mode: raw
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  metrics: []
  all_columns:
  - book_ref
  - book_date
  - booking_total
  - ticket_no
  - ticket_amount
  - fare_conditions
  - flight_id
  - flight_no
  - departure_airport
  - arrival_airport
  - scheduled_departure
  - scheduled_arrival
  - actual_departure
  - actual_arrival
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  order_desc: true
  server_page_length: 10
  row_limit: 1000
  percent_metric_calculation: row_limit
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 3
query_context: '{"datasource":{"id":39,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["book_ref","book_date","booking_total","ticket_no","ticket_amount","fare_conditions","flight_id","flight_no","departure_airport","arrival_airport","scheduled_departure","scheduled_arrival","actual_departure","actual_arrival"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"39__table","viz_type":"table","matrixify_show_column_headers":true,"matrixify_mode_columns":"metrics","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_topn_order_columns":"desc","matrixify_show_row_labels":true,"matrixify_mode_rows":"metrics","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_topn_order_rows":"desc","matrixify_row_height":300,"matrixify_fit_columns_dynamically":true,"matrixify_charts_per_row":3,"query_mode":"raw","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{},"metrics":[],"all_columns":["book_ref","book_date","booking_total","ticket_no","ticket_amount","fare_conditions","flight_id","flight_no","departure_airport","arrival_airport","scheduled_departure","scheduled_arrival","actual_departure","actual_arrival"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"order_desc":true,"server_page_length":10,"row_limit":1000,"percent_metric_calculation":"row_limit","table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[3],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 3eee73cd-97ef-41e4-9612-b86398e28ba8
version: 1.0.0
dataset_uuid: feb1bb0e-6ab8-4afb-a804-b69f94585069
