slice_name: Sunburst - Model -> Revenue -> Class
description: null
certified_by: null
certification_details: null
viz_type: sunburst_v2
params:
  datasource: 33__table
  viz_type: sunburst_v2
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 4
  columns:
  - aircraft_model
  - total_revenue
  - fare_conditions
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: total_revenue
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      uuid: null
      verbose_name: null
      warning_markdown: null
    aggregate: MAX
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: MAX(total_revenue)
    optionName: metric_jgyeria3w9c_ln346qc1f7i
  secondary_metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: fare_conditions
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: STRING
      type_generic: 1
      uuid: null
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT(fare_conditions)
    optionName: metric_vvuvc04q6k8_2cc628wzrej
  adhoc_filters: []
  row_limit: 1000
  linear_color_scheme: dark_blue
  show_labels_threshold: 5
  label_type: key
  number_format: SMART_NUMBER
  date_format: smart_date
  extra_form_data: {}
  dashboards:
  - 3
query_context: '{"datasource":{"id":33,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["aircraft_model","total_revenue","fare_conditions"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_revenue","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"aggregate":"MAX","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"MAX(total_revenue)","optionName":"metric_jgyeria3w9c_ln346qc1f7i"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"fare_conditions","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"uuid":null,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(fare_conditions)","optionName":"metric_vvuvc04q6k8_2cc628wzrej"}],"annotation_layers":[],"row_limit":1000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"33__table","viz_type":"sunburst_v2","matrixify_show_column_headers":true,"matrixify_mode_columns":"metrics","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_topn_order_columns":"desc","matrixify_show_row_labels":true,"matrixify_mode_rows":"metrics","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_topn_order_rows":"desc","matrixify_row_height":300,"matrixify_fit_columns_dynamically":true,"matrixify_charts_per_row":4,"columns":["aircraft_model","total_revenue","fare_conditions"],"metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_revenue","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"aggregate":"MAX","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"MAX(total_revenue)","optionName":"metric_jgyeria3w9c_ln346qc1f7i"},"secondary_metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"fare_conditions","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"uuid":null,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(fare_conditions)","optionName":"metric_vvuvc04q6k8_2cc628wzrej"},"adhoc_filters":[],"row_limit":1000,"linear_color_scheme":"dark_blue","show_labels_threshold":5,"label_type":"key","number_format":"SMART_NUMBER","date_format":"smart_date","extra_form_data":{},"dashboards":[3],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 82f556c0-4a8b-4ef9-b132-0c6d94cd456a
version: 1.0.0
dataset_uuid: df7bcc44-e5ea-4034-ad3d-7cdeb8306cd0
