slice_name: Untitled Query 1234
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 42__table
  viz_type: table
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 3
  query_mode: raw
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup:
    booking_date: true
  all_columns:
  - booking_date
  - total_revenue
  - growth_rate
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    subject: booking_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_by_cols: []
  order_desc: true
  server_page_length: 10
  row_limit: 1000
  percent_metric_calculation: row_limit
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 3
query_context: '{"datasource":{"id":42,"type":"table"},"force":false,"queries":[{"filters":[{"col":"booking_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["booking_date","total_revenue","growth_rate"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"42__table","viz_type":"table","matrixify_show_column_headers":true,"matrixify_mode_columns":"metrics","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_topn_order_columns":"desc","matrixify_show_row_labels":true,"matrixify_mode_rows":"metrics","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_topn_order_rows":"desc","matrixify_row_height":300,"matrixify_fit_columns_dynamically":true,"matrixify_charts_per_row":3,"query_mode":"raw","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{"booking_date":true},"all_columns":["booking_date","total_revenue","growth_rate"],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","subject":"booking_date","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_by_cols":[],"order_desc":true,"server_page_length":10,"row_limit":1000,"percent_metric_calculation":"row_limit","table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[3],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 0a6d586a-7176-428c-9f50-ed29d642cb02
version: 1.0.0
