slice_name: T8. TreeMap - Hot Dst by business class passengers
description: null
certified_by: null
certification_details: null
viz_type: treemap_v2
params:
  datasource: 13__table
  viz_type: treemap_v2
  slice_id: 11
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 4
  groupby:
  - destination_city
  metric:
    aggregate: MAX
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: business_class_passenger_count
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      uuid: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MAX(business_class_passenger_count)
    optionName: metric_cvxsbzl5aqo_k1xdcs8w2m8
    sqlExpression: null
  row_limit: 1000
  sort_by_metric: true
  adhoc_filters:
  - clause: WHERE
    comparator: '1000'
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_4faixlu4u4q_rzkae063eb8
    isExtra: false
    isNew: false
    operator: '>='
    operatorId: GREATER_THAN_OR_EQUAL
    sqlExpression: null
    subject: business_class_passenger_count
  color_scheme: colorsOfRainbow
  show_labels: true
  show_upper_labels: true
  label_type: Key
  number_format: ',.1f'
  date_format: smart_date
  extra_form_data: {}
  dashboards:
  - 2
query_context: '{"datasource":{"id":13,"type":"table"},"force":false,"queries":[{"filters":[{"col":"business_class_passenger_count","op":">=","val":"1000"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["destination_city"],"metrics":[{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"business_class_passenger_count","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(business_class_passenger_count)","optionName":"metric_cvxsbzl5aqo_k1xdcs8w2m8","sqlExpression":null}],"orderby":[[{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"business_class_passenger_count","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(business_class_passenger_count)","optionName":"metric_cvxsbzl5aqo_k1xdcs8w2m8","sqlExpression":null},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"13__table","viz_type":"treemap_v2","slice_id":11,"matrixify_show_column_headers":true,"matrixify_mode_columns":"metrics","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_topn_order_columns":"desc","matrixify_show_row_labels":true,"matrixify_mode_rows":"metrics","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_topn_order_rows":"desc","matrixify_row_height":300,"matrixify_fit_columns_dynamically":true,"matrixify_charts_per_row":4,"groupby":["destination_city"],"metric":{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"business_class_passenger_count","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(business_class_passenger_count)","optionName":"metric_cvxsbzl5aqo_k1xdcs8w2m8","sqlExpression":null},"row_limit":1000,"sort_by_metric":true,"adhoc_filters":[{"clause":"WHERE","comparator":"1000","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_4faixlu4u4q_rzkae063eb8","isExtra":false,"isNew":false,"operator":">=","operatorId":"GREATER_THAN_OR_EQUAL","sqlExpression":null,"subject":"business_class_passenger_count"}],"color_scheme":"colorsOfRainbow","show_labels":true,"show_upper_labels":true,"label_type":"Key","number_format":",.1f","date_format":"smart_date","extra_form_data":{},"dashboards":[2],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: b61997a2-aeb7-458f-acc5-93a3792958a0
version: 1.0.0
dataset_uuid: ef693dd1-329e-46cc-a557-3a507efecf01
